"""empty message

Revision ID: 1d8636824441
Revises: 
Create Date: 2022-12-26 12:50:46.900783

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8636824441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loads',
    sa.Column(
        'load_data_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
    ),
    sa.Column('load_id', sa.String(length=255), nullable=False),
    sa.Column('load_creation_date_time', sa.String(length=255), nullable=False),
    sa.Column('business_unit', sa.String(length=255), nullable=False),
    sa.Column('load_reference_number', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.Column('fuel_surcharge', sa.String(length=255), nullable=True),
    sa.Column('additional_charge', sa.String(length=255), nullable=True),
    sa.Column('number_of_stops', sa.String(length=255), nullable=False),
    sa.Column('total_loaded_miles', sa.String(length=255), nullable=False),
    sa.Column('last_segment_miles', sa.String(length=255), nullable=True),
    sa.Column('pickup_appointment_start_date_time', sa.String(length=255), nullable=False),
    sa.Column('pickup_appointment_end_date_time', sa.String(length=255), nullable=True),
    sa.Column('delivery_appointment_start_date_time', sa.String(length=255), nullable=False),
    sa.Column('delivery_appointment_end_date_time', sa.String(length=255), nullable=True),
    sa.Column('required_equipment', sa.String(length=255), nullable=False),
    sa.Column('hazmat', sa.String(length=255), nullable=False),
    sa.Column('commodity_type', sa.String(length=255), nullable=True),
    sa.Column('load_max_weight', sa.String(length=255), nullable=True),
    sa.Column('critical', sa.String(length=255), nullable=False),
    sa.Column('load_status', sa.String(length=255), nullable=False),
    sa.Column('pickup_status', sa.String(length=255), nullable=False),
    sa.Column('delivery_status', sa.String(length=255), nullable=False),
    sa.Column('pickup_arrival_actual_date_time', sa.String(length=255), nullable=True),
    sa.Column('delivery_arrival_actual_date_time', sa.String(length=255), nullable=True),
    sa.Column(
        'created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
        nullable=True
    ),
    sa.Column('scenario_id', sa.String(length=255), nullable=False),
    sa.Column('load_total_revenue', sa.String(length=255), nullable=True),
    sa.Column('linehaul_revenue', sa.String(length=255), nullable=True),
    sa.Column('pickup_location_id', sa.String(length=255), nullable=False),
    sa.Column('delivery_location_id', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('associated_trip_ids', sa.String(length=255), nullable=True),
    sa.Column(
        'updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
        nullable=False
    ),
    sa.Column('pickup_departure_actual_date_time', sa.String(length=255), nullable=True),
    sa.Column('delivery_departure_actual_date_time', sa.String(length=255), nullable=True),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('timeoff', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('assigned_driver_id', sa.String(length=255), nullable=True),
    sa.Column('load_weight_on_last_segment', sa.String(length=255), nullable=True),
    sa.Column('pickup_arrival_eta', sa.String(length=255), nullable=True),
    sa.Column('pickup_departure_etd', sa.String(length=255), nullable=True),
    sa.Column('delivery_arrival_eta', sa.String(length=255), nullable=True),
    sa.Column('delivery_departure_etd', sa.String(length=255), nullable=True),
    sa.Column('trip_sequence', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('load_data_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loads')
    # ### end Alembic commands ###
